# Ejercicio 1: Preparación del Entorno y el Índice Real

In [ ]:
import pandas as pd
import numpy as np

np.random.seed(123)
legajos_generados = ['TUP-' + str(i) for i in range(1001, 1021)]
carreras_disponibles = ['Programacion', 'Redes', 'Sistemas']
datos_academicos = {
    'Legajo': legajos_generados,
    'Carrera': np.random.choice(carreras_disponibles, 20),
    'Matematica': np.random.randint(2, 11, 20),
    'Bases_Datos': np.random.randint(2, 11, 20),
    'Algoritmos': np.random.randint(2, 11, 20)
}
df_generador = pd.DataFrame(datos_academicos)
df_generador.to_csv('notas_semestre.csv', index=False)
print('Archivo notas_semestre.csv generado con éxito.')

Archivo notas_semestre.csv generado con éxito.

In [ ]:
df_notas = pd.read_csv('notas_semestre.csv')
print('DataFrame leído correctamente.')
print(f'Forma del DataFrame: {df_notas.shape}')
print(f'Columnas: {df_notas.columns.tolist()}')

DataFrame leído correctamente.
Forma del DataFrame: (20, 5)
Columnas: ['Legajo', 'Carrera', 'Matematica', 'Bases_Datos', 'Algoritmos']

In [ ]:
df_notas = df_notas.set_index('Legajo')
print('Índice actualizado a la columna Legajo.')

Índice actualizado a la columna Legajo.

In [4]:
print('Primeras 5 filas (índice ahora es Legajo):')
df_notas.head()

Primeras 5 filas (índice ahora es Legajo):

               Carrera  Matematica  Bases_Datos  Algoritmos
Legajo
TUP-1001      Sistemas           5            7           9
TUP-1002         Redes           6            8           3
TUP-1003      Sistemas           2            4           7
TUP-1004      Sistemas           2            3           9
TUP-1005  Programacion           6           10           4

---

# Ejercicio 2: Auditoría y Navegación Ciega (iloc)

In [ ]:
print('=== AUDITORÍA ESTADÍSTICA ===')
print('Promedios generales por materia:')
df_notas.describe().loc['mean']

=== AUDITORÍA ESTADÍSTICA ===
Promedios generales por materia:

Matematica     5.50
Bases_Datos    6.00
Algoritmos     5.65
Name: mean, dtype: float64

In [ ]:
fila_decima = df_notas.iloc[9]
print('Décima fila (índice 9):')
print(fila_decima)

Décima fila (índice 9):
Carrera        Redes
Matematica         6
Bases_Datos        8
Algoritmos         3
Name: TUP-1010, dtype: object

In [ ]:
print('Primeras 3 filas y primeras 2 columnas:')
df_notas.iloc[:3, :2]

Primeras 3 filas y primeras 2 columnas:

           Carrera  Matematica
Legajo
TUP-1001  Sistemas           5
TUP-1002     Redes           6
TUP-1003  Sistemas           2

---

# Ejercicio 3: Operando al Paciente (loc)

In [8]:
df_notas.loc['TUP-1005', 'Bases_Datos'] = 9
print('Nota de TUP-1005 en Bases_Datos actualizada a 9.')

Nota de TUP-1005 en Bases_Datos actualizada a 9.

In [9]:
df_notas.loc['TUP-1018', 'Matematica'] = 7
print('Nota de TUP-1018 en Matematica actualizada a 7.')

Nota de TUP-1018 en Matematica actualizada a 7.

In [10]:
df_verificacion = df_notas.loc[['TUP-1005', 'TUP-1018']]
print('=== VERIFICACIÓN DE MODIFICACIONES ===')
df_verificacion

=== VERIFICACIÓN DE MODIFICACIONES ===

               Carrera  Matematica  Bases_Datos  Algoritmos
Legajo
TUP-1005  Programacion           6            9           4
TUP-1018      Sistemas           7            6           5

---

# Ejercicio 4: Integración - Máscaras Booleanas Múltiples

In [ ]:
mascara = (
    (df_notas['Carrera'] == 'Programacion') &
    (df_notas['Algoritmos'] >= 8)
)
print('Máscara booleana construida.')
print(f'Alumnos que cumplen las condiciones: {mascara.sum()}')

Máscara booleana construida.
Alumnos que cumplen las condiciones: 1

In [12]:
df_destacados = df_notas[mascara]
print('DataFrame filtrado guardado en df_destacados.')

DataFrame filtrado guardado en df_destacados.

In [13]:
print('=== ALUMNOS DESTACADOS EN PROGRAMACIÓN ===')
df_destacados

=== ALUMNOS DESTACADOS EN PROGRAMACIÓN ===

               Carrera  Matematica  Bases_Datos  Algoritmos
Legajo
TUP-1017  Programacion           5            8           8

---

# Ejercicio 5: El Desafío Final - Estadística Vectorizada

In [14]:
df_redes = df_notas[df_notas['Carrera'] == 'Redes']
print(f'Alumnos de Redes: {len(df_redes)}')

Alumnos de Redes: 7

In [15]:
matematica_redes = df_redes['Matematica']
print('Columna Matemática extraída.')

Columna Matemática extraída.

In [16]:
promedio = matematica_redes.mean()
print(f'📊 PROMEDIO DE MATEMÁTICA (Carrera: Redes): {promedio:.2f}')

📊 PROMEDIO DE MATEMÁTICA (Carrera: Redes): 6.14